In [9]:
# Q1
import numpy as np

def nozero(arr):
    return np.all(arr != 0)

arr1 = np.array([1, 2, 3, 14, 86])
arr2 = np.array([1, 2, 3, 14, 0])

print("arr1 is:", nozero(arr1))
print("arr2 is:", nozero(arr2))

arr1 is: True
arr2 is: False


In [13]:
# Q2
def nozero(arr):
    return np.any(arr != 0)

arr1 = np.array([0, 0, 0, 0, 0])
arr2 = np.array([0, 0, 3, 0, 0])

print("arr1 is:", nozero(arr1))
print("arr2 is:", nozero(arr2))

arr1 is: False
arr2 is: True


In [19]:
# Q3

def element_wise_comparison(arr1, arr2, tolerance):
    return np.isclose(arr1, arr2, atol=tolerance)

# Example arrays
array1 = np.array([1.0, 2.5, 3.0, 4.0])
array2 = np.array([1.05, 2.499, 3, 4.06])

tolerance_value = 0.05

result = element_wise_comparison(array1, array2, tolerance_value)
print("Element-wise comparison result:", result)

Element-wise comparison result: [ True  True  True False]


In [24]:
#Q4

zeros_arr = np.zeros(10)
ones_arr = np.ones(10)
fives_arr = np.full(10,5)
print(zeros_arr)
print(ones_arr)
print(fives_arr)

all_array = np.concatenate((zeros_arr, ones_arr, fives_arr)) #concatenates the three arrays into a single array

print("Combined Array:", all_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
Combined Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [26]:
# Q5

arr = np.arange(30 , 71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [27]:
# Q6

identity_matrix = np.identity(3)
print("3X3 identity_matrix")
identity_matrix

3X3 identity_matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#Q7
random_number = np.random.random() # from 0 to 1 only

print("Random Number:", random_number)

random_number2 = np.random.uniform(1, 3) #from any given number to any given number

print("Random Number:", random_number2)

Random Number: 0.5262480142499361
Random Number: 2.24796672153901


In [37]:
# Q8

random_array = np.random.randn(15)

print("Random Array from Standard Normal Distribution:")
print(random_array)

Random Array from Standard Normal Distribution:
[-0.17632916  0.78851391  0.20859822 -0.0239902   1.50271453  0.65399836
 -0.1211108  -0.398096    0.57359519 -0.1850402   0.82936749 -0.86011663
  1.18544278 -1.3200259  -0.58404383]


In [39]:
# Q9

vector = np.arange(15, 56)
vector[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [42]:
# Q10

vector = np.random.randint(0, 11, 5) #lower_bound, upper_bound, size=vector_length
vector

array([0, 1, 9, 2, 7])

In [45]:
# Q11

size = 10
matrix = np.zeros((size, size))
matrix[0, :] = 1  # Top border
matrix[-1, :] = 1  # Bottom border
matrix[:, 0] = 1  # Left border
matrix[:, -1] = 1  # Right border
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
#Q12

matrix = np.diag([1 ,2 ,3,4,5])

matrix


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [53]:
#Q13

size = 4

matrix = np.zeros((size, size))
matrix[::2, 1::2] = 1 #sets the elements in odd-numbered rows and even-numbered columns to 1.
matrix[1::2, ::2] = 1 # sets the elements in even-numbered rows and odd-numbered columns to 1.

print(matrix)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [60]:
#Q14

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])
np.savez_compressed('arrays.npz', arr1=array1, arr2=array2)

loaded_data = np.load('arrays.npz')
loaded_array1 = loaded_data['arr1']
loaded_array2 = loaded_data['arr2']

print("Loaded Array 1:", loaded_array1)
print("Loaded Array 2:", loaded_array2)


Loaded Array 1: [1 2 3 4 5]
Loaded Array 2: [10 20 30 40 50]


In [68]:
# Q14 again
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])
#to save single array
np.save(file = "arr.npy" , arr = array1)
np.load(file = "arr.npy")
#to save multible arrays
np.savez(file="arayz.npz" , arr1 = array1 , arr2 = array2 )
tmp = np.load(file="arayz.npz")
list(tmp.keys())

['arr1', 'arr2']

In [70]:
tmp["arr1"]

array([1, 2, 3, 4, 5])

In [71]:
tmp["arr2"]

array([10, 20, 30, 40, 50])

In [ ]:
#Q15

# m4 fahem el so2al


In [77]:
#Q16
given_number = 3
arr = np.array([0.5,1,2,3,4,5,6])
big = arr > given_number
less = arr < given_number
print("bigger than 3 : ", arr[big])
print("less than 3 : ", arr[less])

bigger than 3 :  [4. 5. 6.]
less than 3 :  [0.5 1.  2. ]
